# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dc454e6e0327361da3b26ca3fa7535c925ca9ac4a91e239b4815ee80657469aa7e8d5cd574f6504bb6c4f507dfbaeb14b6a17c6147629b163749e205a55224c

test:
  secret_key_base: c8d754f24e91693488714c16ea8a554c3a54fc2b0700e4d66b6233873408425fc24655cdbc431bd3e8328b19bb50f78e0be907e73634bb77b5c223800c803b1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
